name: 'Bink'
version: '1.0.0'
config-version: 2

profile: 'Bink_New'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

models:
  Bink:
    prod:
      +database: "PROD"
      bink:
        +schema: "BINK"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      bink_secure:
        +schema: "BINK_SECURE"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER']
      service_data:
        +schema: "SERVICE_DATA"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER']
    staging:
      +database: "STAGING"
      staging:
        +schema: "STAGING"
        materialized: view
      transformation:
        +schema: "TRANSFORMATION"
        materialized: view
        config:
          grants:
            select: ['ANALYTICS_ENGINEER']
    metrics_staging:
      +database: "METRICS_STAGING"
      +materialized: view
      warehouse:
        +schema: "WAREHOUSE"      
      lookup:
        +schema: "LOOKUP"
      retailer_lookup:
        +schema: "RETAILER_LOOKUP"
      metrics_transformation:
        +schema: "TRANSFORMATION"
    metrics:
      +database: "METRICS"
      loyalty_cards:
        +schema: "LOYALTY_CARDS"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      transactions:
        +schema: "TRANSACTIONS"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      users:
        +schema: "USERS"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      voucher:
        +schema: "VOUCHER"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      jira:
        +schema: "JIRA"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
    output:
      +database: "OUTPUT"
      lbg:
        +schema: "LBG"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      commercial:
        +schema: "COMMERCIAL"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      jira:
        +schema: "JIRA"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      retailer__the_works:
        +schema: "RETAILER__THE_WORKS"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      retailer__itsu:
        +schema: "RETAILER__ITSU"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      retailer__viator:
        +schema: "RETAILER__VIATOR"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']
      self_service:
        +schema: "SELF_SERVICE"
        materialized: table
        config:
          grants:
            select: ['ANALYTICS_ENGINEER', 'BI_ANALYST']


seeds:
  Bink:
    lookup:
      +database: "RAW" #to be moved to raw eventually
      +schema: "BINK_LOOKUP"
    retailer:
      +database: "RAW"
      +schema: "RETAILER_LOOKUP"
        
  elementary:
    +database: 'MONITORING'
    +schema: 'MONITORING'
    +materialized: table #ignore
    +transient: false
vars:
 dbt_artifacts_database: 'DEV'
 dbt_artifacts_schema: 'MONITORING'
 qa_data_suffix: ''
 retailor_start_date: {"The Works": "2023-08-22", "itsu": "2023-09-11 22:40:00"}
 retailor_exclusion_lists: {"The Works": {"CHANNEL": ['BARCLAYS', 'BINK']}}
