name: 'Bink'
version: '1.0.0'
config-version: 2

profile: 'Bink_New'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

models:
  Bink:
    prod:
      +database: "PROD"
      bink:
        +schema: "BINK"
        materialized: table
      bink_secure:
        +schema: "BINK_SECURE"
        materialized: table
      service_data:
        +schema: "SERVICE_DATA"
        materialized: table

    staging:
      +database: "STAGING"
      staging:
        +schema: "STAGING"
        materialized: view
      transformation:
        +schema: "TRANSFORMATION"
        materialized: view
    
    metrics_staging:
      +database: "METRICS_STAGING"
      +materialized: view
      warehouse:
        +schema: "WAREHOUSE"      
      lookup:
        +schema: "LOOKUP"
      metrics_transformation:
        +schema: "TRANSFORMATION"

    metrics:
      +database: "METRICS"
      loyalty_cards:
        +schema: "LOYALTY_CARDS"
        materialized: table
      transactions:
        +schema: "TRANSACTIONS"
        materialized: table
      users:
        +schema: "USERS"
        materialized: table
      voucher:
        +schema: "VOUCHER"
        materialized: table

    output:
      +database: "OUTPUT"
      lbg:
        +schema: "LBG"
        materialized: table
      commercial:
        +schema: "commercial"
        materialized: table

seeds:
  Bink:
    +database: "ANALYTICS"
    +schema: "BINK_LOOKUP"
        
  elementary:
    +database: 'MONITORING'
    +schema: 'MONITORING'
    +materialized: table
    +transient: false
vars:
 dbt_artifacts_database: 'DEV'
 dbt_artifacts_schema: 'MONITORING'
