name: 'Bink'
version: '1.0.0'
config-version: 2

profile: 'Bink'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

models:
  Bink:
    staging:
      +schema: "BINK_STAGING"
      materialized: view
    transformations:
      +schema: "BINK_TRANSFORMED"
      materialized: view
    marts:
        bink:
          +schema: "BINK"
          materialized: table
        bink_secure:
          +schema: "BINK_SECURE"
          materialized: table

vars:
 dbt_artifacts_database: 'DEV'
 dbt_artifacts_schema: 'BINK_MONITORING'
