name: 'Bink'
version: '1.0.0'
config-version: 2

profile: 'Bink'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

seeds:
  Bink:
    +schema: "BINK_LOOKUP"

models:
  Bink:
    staging:
      +schema: "BINK_STAGING"
      materialized: view
    transformations:
      +schema: "BINK_TRANSFORMED"
      materialized: view
    marts:
      +schema: "BINK"
      materialized: table
  elementary:
    +schema: 'BINK_MONITORING'
    +materialized: table
    +transient: false