version: 2

sources:
  - name: Bink
    description: Bink
    database: RAW
    schema: HERMES
    tags: ['source']

    tables:
      - name: USER
        identifier: USER
        description: Table contains all current users.
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
          - name: 'UID'
            description: userID of user table
            tests:
              - unique
              - not_null
      - name: HISTORY_USER
        identifier: HISTORY_HISTORICALCUSTOMUSER
        description: Table contains all updates to users.
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null

      