version: 2

sources:
  - name: Hermes
    description: Heremes schema
    database: RAW
    schema: HERMES
    tags: ['source']

    tables:
      - name: USER
        identifier: USER
        description: Table contains all current users.
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
          - name: 'UID'
            description: userID of user table
            tests:
              - unique
              - not_null
              
      - name: SCHEME_SCHEMEACCOUNT
        identifier: SCHEME_SCHEMEACCOUNT
        description: This table contains information on the individual loyaltycards
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of schemeaccount table
            tests:
              - unique
              - not_null
          # - name: 'TRANSACTION_ID'
          #   description: Business Primary key of user table
          #   tests:
          #     - unique
          #     - not_null
              
      - name: HISTORY_USER
        identifier: HISTORY_HISTORICALCUSTOMUSER
        description: Table contains all updates to users.
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
      - name: PAYMENT_ACCOUNT
        identifier: PAYMENT_CARD_PAYMENTCARDACCOUNT
        description: Table contains payment account data
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
      - name: PAYMENT_STATUS
        identifier: PAYMENT_CARD_PROVIDERSTATUSMAPPING
        description: Table contains payment status'
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
      - name: PAYMENT_CARD
        identifier: PAYMENT_CARD_PAYMENTCARD
        description: Table contains payment card details - e.g. barclays, amex
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
              
      - name: SCHEME_SCHEME
        identifier: SCHEME_SCHEME
        description: This table contains information about the individual loyalty plans.
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of scheme table
            tests:
              - unique
              - not_null

      - name: SCHEME_CATEGORY
        identifier: SCHEME_CATEGORY
        description: Look up table for loyalty plan categorys
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of scheme category table
            tests:
              - unique
              - not_null

  - name: Harmonia
    description: Harmonia schema, containing transaction data
    database: RAW
    schema: HARMONIA
    tags: ['source']

    tables:
      - name: payment_transaction
        identifier: PAYMENT_TRANSACTION
        description: Table contains transactions
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
          - name: 'TRANSACTION_ID'
            description: Business Primary key of user table
            tests:
              - unique
              - not_null
      - name: matched_transaction
        identifier: MATCHED_TRANSACTION
        description: Table contains transactions
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
          - name: 'TRANSACTION_ID'
            description: Business Primary key of user table
            tests:
              - unique
              - not_null
      - name: export_transaction
        identifier: EXPORT_TRANSACTION
        description: Table contains transactions
        freshness:
          warn_after: { count: 2, period: hour }
        meta:
          elementary:
            timestamp_column: '_AIRBYTE_EMITTED_AT'
        tests:
            - elementary.table_anomalies
            - elementary.schema_changes
        columns:
          - name: 'ID'
            description: Primary key of user table
            tests:
              - unique
              - not_null
          - name: 'TRANSACTION_ID'
            description: Business Primary key of user table
            tests:
              - unique
              - not_null
              
